# Hyperparamter for ddpg
# Algortihm Parameters
gamma: 0.8 # reward decay
lr_a: 0.0001 # learning rate for actor
lr_c: 0.001 # learning rate for critic
tau: 0.01 # soft replacement
memory_size: 500
batch_size: 64
nepisodes: 500
nsteps: 200
